"""Does `StatementClassification` return the same answer twice for the same text?

WHY THIS EXISTS
===============
`probe_tetrad_pole.py` measured a prompt fix by comparing two runs it declared
matched — "held fixed: population, tier, auditor, audit prompt; only the
generation prompt moves". That was false, and the probe's own readout is what
exposed it. The classification of the 12 poles differed between runs, and the
branch it returns is not metadata: `lookup_aspect_apex(parent, position)` uses it
to select the apex row interpolated into `_tetrad_prompt`. Four of twelve poles
therefore taught the generator from a different apex on the second run.

Three readings of those 12 poles (baseline / run 1 / run 2) gave:

  Buy the cofounder out now       Integrity   Integrity   Integrity    stable
  Retain the cofounder            Integrity   Integrity   Integrity    stable
  Take full ownership solo        Integrity   Integrity   Integrity    stable
  Collective                      Integrity   Integrity   Integrity    stable
  Mandate uniform process         Integrity   Integrity   Integrity    stable
  Let teams own their process     Flexibility Flexibility Flexibility  stable
  Individual                      SIMPLE      SIMPLE      SIMPLE       stable
  Secure the anchor accounts      Integrity   Resilience  Integrity    wobbles
  Security                        Integrity   Integrity   Resilience   wobbles
  Wait until unknowns resolve     Fidelity    Integrity   Fidelity     wobbles
  Decide now and commit           Flexibility Fire        Fire         CROSSES
  Freedom                         Water       Air         Fire         3 for 3

Two claims came out of that, and they have very different evidential standing.
The first — that classification is unstable — is a direct reading of the data.
The second — that the split is by FORM, long concrete course-of-action stable and
short abstract noun not — is a hypothesis GENERATED by staring at those 12 rows.
Testing it on those same 12 rows would be circular, which is why Set B below is
new text written for the purpose.

This matters beyond the probe. Per CLAUDE.md the branch also feeds HS, which
gates `_rank_polarities` at `HS_THRESHOLD=0.7`; and the SIMPLE/COMPLEX boundary
is "the most leverage-dense prompt in the extraction pipeline", because SIMPLE
hardcodes HS to 1.0 and inflates every polarity past that gate.

PRE-REGISTRATION (written before any statement was classified, 2026-08-20)
=========================================================================
Population: 48 statements x 6 readings = 288 classifications, all on the WEAK
tier — the tier that produced the observation and that the archive ran on. A
stable result on a stronger model would not retire this.

  SET A  (12, replication)  The exact 12 poles `probe_tetrad_pole.py` classified,
                            verbatim, so the 3-reading observation gets a 6-reading
                            test on the same text.
  SET B  (36, form test)    12 domains x 3 arms, matched by domain so domain is not
                            the confound:
                              SHORT_ABSTRACT  a bare noun ("Autonomy")
                              SHORT_CONCRETE  a 3-4 word action ("Delay the launch")
                              LONG_CONCRETE   a 9-14 word course of action

Primary endpoint: BRANCH UNANIMITY — a statement is unanimous iff all 6 readings
return the same branch. Chosen over "modal agreement rate" because the downstream
consumer takes ONE reading: a statement that is right 4 times in 6 still teaches
the generator a different apex whenever it is not.

E1, Set A replication — unanimous count out of 12:
  * CONFIRMS INSTABILITY  <= 8/12
  * CONTRADICTS IT        12/12. The 3-reading drift was an unlucky sample and
                          this whole line of inquiry was noise.
  * PARTIAL               9..11/12.

E2, Set B form hypothesis (the new claim), 12 per arm:
  * FORM EFFECT REAL   LONG_CONCRETE unanimous - SHORT_ABSTRACT unanimous >= 6
                       AND Fisher two-sided p < 0.05. Both, because at 12 per arm
                       a gap of 6 is roughly what p<0.05 needs, and a bare count
                       would over-read a smaller one.
  * NO FORM EFFECT     gap <= 2.
  * INDETERMINATE      3..5.
  SHORT_CONCRETE is the discriminator and is reported, not gated: if it tracks
  LONG_CONCRETE then CONCRETENESS drives stability; if it tracks SHORT_ABSTRACT
  then LENGTH does. Two arms could not have told those apart.

Severity secondaries, reported separately because each has a different downstream
consequence and a different fix:
  * SIMPLE/COMPLEX FLIP — highest severity, independent of any branch count. One
    flip forces HS to 1.0 on some readings and not others, which moves the polarity
    across `HS_THRESHOLD=0.7`. A statement that flips is a defect even if its
    COMPLEX readings are unanimous on branch.
  * TAXONOMY CROSS (`System(` <-> `Elements(`) — swaps the apex vocabulary
    wholesale rather than picking a neighbouring row.
  * DOMAIN DRIFT (General / Engineering / Ecology / Institutions / Love) — the
    domain is also an argument to the apex lookup, so it changes the taught apex
    even when the branch holds. Deliberately NOT folded into branch unanimity, so
    that a stable-branch / drifting-domain statement cannot be scored as clean.

Pre-declared confound: the three arms bundle length, concreteness, and
naming-an-action. Three arms separate length from concreteness; nothing here
isolates "names an action". Any positive result is about FORM as a bundle and the
write-up must say so rather than claiming abstractness specifically.

Pre-declared non-confound: no graph is touched and no generation runs, so there
is no ordering, no scope, and no shared cache. Each reading constructs a fresh
`StatementClassification`. The only variance is the provider's.

RESULT (2026-08-20, 288 classifications over 47 unique texts, weak tier)
=======================================================================
"Security" appears in both sets verbatim, so 48 rows resolve to 47 texts.

E1, Set A replication: 6/12 branch-unanimous. INSTABILITY CONFIRMED — the bar
was <= 8/12 and it cleared with margin. The 3-reading table above understated
it: 7 of those 12 looked stable across 3 readings, 6 survive 6. Nothing here
was an unlucky sample.

E2, the form hypothesis: REFUTED on the registered endpoint.

  SHORT_ABSTRACT   6/12 unanimous
  SHORT_CONCRETE   5/12
  LONG_CONCRETE    7/12
  gap = 1 (needed >= 6), Fisher two-sided p = 1.0000 (needed < 0.05)

Both prongs missed, and gap <= 2 is the pre-registered NO FORM EFFECT band, so
this is a positive null and not an underpowered miss: 12 fresh long concrete
courses of action are no more stably classified than 12 bare nouns. The Set A
pattern that generated this hypothesis was me reading form onto 12 rows that
happened to line up. It does not reproduce on text written to test it, which is
exactly what the non-circular Set B was for. The SHORT_CONCRETE discriminator is
therefore uninterpretable by construction and the readout now says so instead of
naming a winner.

Severity secondaries:

  * SIMPLE/COMPLEX FLIP: 0 of 47. The highest-severity mode does not occur. The
    boundary CLAUDE.md calls "the most leverage-dense prompt in the extraction
    pipeline" is the one thing here that is solid — no statement was SIMPLE on
    one reading and COMPLEX on another, so nothing silently forced HS to 1.0.
    This is the load-bearing reassurance in the whole run.

  * TAXONOMY CROSS: 5 of 47 — Freedom (Water/Flexibility), Decide now and commit
    (Flexibility/Fire), Speed (Fire/Exchange), Growth (Flexibility/Fire),
    Caution (Water/Resilience). All five are short: four bare nouns and one
    4-word phrase. By arm within Set B: SHORT_ABSTRACT 3/12, SHORT_CONCRETE
    0/12, LONG_CONCRETE 0/12.

  * DOMAIN DRIFT: 12 of 47, spread across all three arms (Freedom and Autonomy
    and Transparency General/Institutions, Security Engineering/General,
    Pair-program every feature Engineering/Institutions, ...). This is why it
    was kept out of branch unanimity: folding branch and domain together, only
    18 of 47 texts (38%) return the SAME (family, domain, branch) on all six
    readings. Per arm, any-instability: Set A 8/12, SHORT_ABSTRACT 8/12,
    SHORT_CONCRETE 8/12, LONG_CONCRETE 6/12 (Set A vs LONG_CONCRETE p = 0.68).
    The taught apex is less stable than the primary endpoint alone suggests.

A hypothesis GENERATED HERE, banked as untested, not as a finding
----------------------------------------------------------------
Form failed on how OFTEN a statement is unstable, but every taxonomy cross in
the run is a short statement. Pooling the two comparison arms gives 3/12 vs 0/24,
p = 0.0308 — and that number must not be reported as a result. The pooling was
chosen after seeing which grouping reached significance; the unpooled comparison
that was equally available (SHORT_ABSTRACT 3/12 vs SHORT_CONCRETE 0/12) is
p = 0.2174; no threshold was pre-registered on this channel; and it is one of
several secondary comparisons on one dataset. It is the same "stare at the rows
until a pattern appears" move that produced the hypothesis this run just killed,
so it gets the same treatment: written down, owed a pre-registered test on new
text before anyone acts on it. If it survives one, the readable mechanism is
that a bare noun gives the classifier nothing to anchor a family on, so it
crosses System/Elements rather than picking a neighbouring branch — a severity
effect, not a frequency one.

What this run does and does not license
--------------------------------------
Licensed: `probe_tetrad_pole.py`'s "held fixed, only the generation prompt moves"
was wrong, and quantifiably so — half its population changes branch across
readings and 62% changes the taught apex. Any future measurement downstream of
this classifier must either pin the classification or report it as a confound.
NOT licensed: any claim about which statements are unstable, or any prompt edit
to `statement_classification.py` justified by form. The cause is unidentified.

Run:
  poetry run pytest tests/e2e/probe_classifier_stability.py -s --real-llm
  poetry run pytest tests/e2e/probe_classifier_stability.py -s   (free: prints the
      population and the arm balance, no provider calls)
"""

from __future__ import annotations

import asyncio
import collections
from typing import Optional

import pytest

from dialectical_framework.concerns.statement_classification import (
    ELEMENTAL_PREFIX, SYSTEMIC_PREFIX, ClassificationResult,
    StatementClassification, parse_meaning_uri)
from e2e.config import E2EConfig
from e2e.modelctx import using_model

pytestmark = [pytest.mark.llm]

_READINGS = 6

#: The 12 poles `probe_tetrad_pole.py` classifies, verbatim. Changing any string
#: here breaks the comparison with the three readings recorded in that file's
#: docstring, which is the only reason this list is duplicated rather than
#: imported — importing would let a future edit to _TENSIONS silently redefine
#: this probe's replication set.
_SET_A: list[str] = [
    "Secure the anchor accounts before removing the cofounder",
    "Buy the cofounder out now and consolidate ownership",
    "Retain the cofounder in the key customer relationships",
    "Take full ownership and run the company solo",
    "Freedom",
    "Security",
    "Individual",
    "Collective",
    "Mandate uniform process discipline across all teams",
    "Let teams own their process where they demonstrably deliver",
    "Decide now and commit",
    "Wait until the load-bearing unknowns resolve",
]

#: (domain, SHORT_ABSTRACT, SHORT_CONCRETE, LONG_CONCRETE). New text, written for
#: E2 — the form hypothesis came from Set A, so Set A cannot test it. Matched by
#: domain across arms so a difference between arms is form, not subject matter.
_FORM_TRIPLETS: list[tuple[str, str, str, str]] = [
    (
        "autonomy",
        "Autonomy",
        "Let teams choose tools",
        "Let each team choose its own tooling wherever delivery stays on schedule",
    ),
    (
        "security",
        "Security",
        "Require two-factor login",
        "Require two-factor authentication on every account before the audit closes",
    ),
    (
        "speed",
        "Speed",
        "Ship the beta Friday",
        "Ship the beta on Friday and fix defects from user reports afterwards",
    ),
    (
        "transparency",
        "Transparency",
        "Publish all salary bands",
        "Publish every salary band company-wide before the next compensation review",
    ),
    (
        "focus",
        "Focus",
        "Cut the side projects",
        "Cut every side project and put the whole team on the core product",
    ),
    (
        "growth",
        "Growth",
        "Double the sales team",
        "Double the sales headcount now and accept a lower close rate per rep",
    ),
    (
        "quality",
        "Quality",
        "Block releases on tests",
        "Block every release until the full regression suite passes without exceptions",
    ),
    (
        "trust",
        "Trust",
        "Stop reviewing expenses",
        "Stop pre-approving expenses and audit a random sample each quarter instead",
    ),
    (
        "ownership",
        "Ownership",
        "Buy out the investor",
        "Buy out the seed investor now and consolidate the cap table under founders",
    ),
    (
        "caution",
        "Caution",
        "Delay the launch",
        "Delay the launch until the load-bearing regulatory questions are answered",
    ),
    (
        "collaboration",
        "Collaboration",
        "Pair on all features",
        "Pair-program every feature so knowledge never sits with one engineer",
    ),
    (
        "independence",
        "Independence",
        "Run the company solo",
        "Run the company solo and hire contractors instead of taking on a partner",
    ),
]

_ARMS = ("SHORT_ABSTRACT", "SHORT_CONCRETE", "LONG_CONCRETE")

# Pre-registered decision thresholds, named so the readout cannot quietly use
# different numbers than the docstring.
_PREREG_E1_UNSTABLE_CEILING = 8      # <= this many unanimous of 12 => instability
_PREREG_E2_GAP = 6                   # LONG_CONCRETE - SHORT_ABSTRACT unanimity
_PREREG_E2_NULL_GAP = 2              # <= this => no form effect


def _population() -> list[tuple[str, str, str]]:
    """(set_name, arm, text) for every statement, deduplicated within a set.

    Set A and Set B overlap on nothing by construction — Set A's short nouns are
    Freedom/Security/Individual/Collective and Set B's are different words — but
    "Security" appears in BOTH, and deliberately: it is the one statement that
    gets a 6-reading result usable in E1 and E2 at once. It is counted once in
    each set's tally and classified once, so the readings are shared, not doubled.
    """
    rows: list[tuple[str, str, str]] = [("A", "SET_A", text) for text in _SET_A]
    for _domain, short_abstract, short_concrete, long_concrete in _FORM_TRIPLETS:
        rows.append(("B", "SHORT_ABSTRACT", short_abstract))
        rows.append(("B", "SHORT_CONCRETE", short_concrete))
        rows.append(("B", "LONG_CONCRETE", long_concrete))
    return rows


def _distinct_texts() -> list[str]:
    """Every text needing readings, once. Preserves first-seen order."""
    seen: dict[str, None] = {}
    for _set_name, _arm, text in _population():
        seen.setdefault(text, None)
    return list(seen)


def _family_of(meaning: str) -> str:
    if meaning.startswith(SYSTEMIC_PREFIX):
        return "System"
    if meaning.startswith(ELEMENTAL_PREFIX):
        return "Elements"
    return "Simple" if "Simple" in meaning else "?"


def _reading_key(result: ClassificationResult) -> tuple[str, str, str, str]:
    """(simple, family, domain, branch) — everything that changes the taught apex.

    `leaf` is excluded on purpose: `lookup_aspect_apex` keys on branch (+domain),
    so a differing leaf does not change what the generator is taught and folding
    it in would inflate the instability count.
    """
    if result.is_simple:
        return ("SIMPLE", "Simple", "-", "-")
    domain, _category, branch, _leaf = parse_meaning_uri(result.meaning)
    return (
        "COMPLEX",
        _family_of(result.meaning),
        domain or "?",
        branch or "?",
    )


def _fisher_exact_two_sided(a: int, b: int, c: int, d: int) -> float:
    """p-value for [[a,b],[c,d]], no SciPy. Same convention as the other probes."""
    from math import comb

    n = a + b + c + d
    row1, col1 = a + b, a + c

    def prob(x: int) -> float:
        return comb(row1, x) * comb(n - row1, col1 - x) / comb(n, col1)

    lo = max(0, col1 - (n - row1))
    hi = min(row1, col1)
    observed = prob(a)
    return min(1.0, sum(p for x in range(lo, hi + 1)
                        if (p := prob(x)) <= observed + 1e-9))


# --- Free self-check ----------------------------------------------------------


def test_the_population_matches_the_preregistration() -> None:
    """No LLM. Prints the plan and checks the arms are balanced."""
    rows = _population()
    texts = _distinct_texts()
    print("\n=== pre-registered population ===")
    print(f"Set A (replication) : {len(_SET_A)} statements")
    print(f"Set B (form test)   : {len(_FORM_TRIPLETS)} domains x 3 arms = "
          f"{3 * len(_FORM_TRIPLETS)}")
    print(f"rows                : {len(rows)}")
    print(f"distinct texts      : {len(texts)}")
    print(f"readings each       : {_READINGS}")
    print(f"provider calls      : {len(texts) * _READINGS}")
    print(f"\nE1 instability if <= {_PREREG_E1_UNSTABLE_CEILING}/12 unanimous")
    print(f"E2 form effect if gap >= {_PREREG_E2_GAP} AND p < 0.05; "
          f"null if gap <= {_PREREG_E2_NULL_GAP}")

    print("\n=== Set B, by arm ===")
    for arm in _ARMS:
        members = [t for _s, a, t in rows if a == arm]
        print(f"  {arm:<15} n={len(members)}  e.g. {members[0]!r}")

    # Every arm must be the same size, or a unanimity-count comparison between
    # arms is comparing different denominators.
    sizes = {arm: len([1 for _s, a, _t in rows if a == arm]) for arm in _ARMS}
    assert len(set(sizes.values())) == 1, sizes
    assert sizes["LONG_CONCRETE"] == len(_FORM_TRIPLETS)
    # Set A must stay verbatim-comparable to probe_tetrad_pole's three readings.
    assert len(_SET_A) == 12
    # The form arms must actually differ in form, or E2 measures nothing.
    for domain, short_abstract, short_concrete, long_concrete in _FORM_TRIPLETS:
        assert len(short_abstract.split()) == 1, domain
        assert 3 <= len(short_concrete.split()) <= 4, domain
        assert 9 <= len(long_concrete.split()) <= 14, domain


# --- The measurement ----------------------------------------------------------


@pytest.fixture
def cleanup_graph_db():
    """DB-free: classification touches no graph. Overrides the autouse fixture so
    this probe does not contend with a concurrent graph-test run."""
    yield


@pytest.fixture
def cleanup_test_graph_data():
    yield


@pytest.mark.real_llm
@pytest.mark.asyncio
async def test_the_same_text_classifies_the_same_way_six_times(di_container) -> None:
    config = E2EConfig.from_env()
    model = config.tiers["weak"]
    texts = _distinct_texts()

    print(f"\n=== {len(texts)} texts x {_READINGS} readings on the WEAK tier: "
          f"{model} ===", flush=True)

    async def read(text: str) -> Optional[ClassificationResult]:
        try:
            return await StatementClassification().resolve(statement=text)
        except Exception as exc:  # noqa: BLE001 - a dead reading is data, not a stop
            print(f"  !! {text[:40]!r}: {type(exc).__name__}: {exc}", flush=True)
            return None

    readings: dict[str, list[ClassificationResult]] = {}
    with using_model(di_container, model):
        # One round at a time: every text gets reading k before any text gets
        # reading k+1. If the provider drifts during the run, the drift is spread
        # across all texts instead of landing entirely on whichever ones happened
        # to be classified late.
        for round_index in range(1, _READINGS + 1):
            results = await asyncio.gather(*(read(t) for t in texts))
            for text, result in zip(texts, results):
                if result is not None:
                    readings.setdefault(text, []).append(result)
            done = sum(len(v) for v in readings.values())
            print(f"  round {round_index}/{_READINGS}: {done} readings so far",
                  flush=True)

    # --- per-statement tallies -------------------------------------------------

    keys: dict[str, list[tuple[str, str, str, str]]] = {
        text: [_reading_key(r) for r in rs] for text, rs in readings.items()
    }
    short = 0

    def unanimous_branch(text: str) -> bool:
        return len({k[3] for k in keys.get(text, [])}) == 1

    def flips_simple(text: str) -> bool:
        return len({k[0] for k in keys.get(text, [])}) > 1

    def crosses_taxonomy(text: str) -> bool:
        families = {k[1] for k in keys.get(text, []) if k[1] != "Simple"}
        return len(families) > 1

    def drifts_domain(text: str) -> bool:
        return len({k[2] for k in keys.get(text, []) if k[2] != "-"}) > 1

    print("\n=== every statement, all readings ===")
    for set_name, arm, text in _population():
        got = keys.get(text, [])
        if len(got) < _READINGS:
            short += 1
        tally = collections.Counter(
            f"{k[3]}" if k[0] == "COMPLEX" else "SIMPLE" for k in got
        )
        spread = "  ".join(f"{branch}x{n}" for branch, n in tally.most_common())
        flags = []
        if flips_simple(text):
            flags.append("SIMPLE-FLIP")
        if crosses_taxonomy(text):
            flags.append("TAXONOMY-CROSS")
        if drifts_domain(text):
            doms = sorted({k[2] for k in got if k[2] != "-"})
            flags.append(f"DOMAIN-DRIFT({'/'.join(doms)})")
        mark = "  " if unanimous_branch(text) else "!!"
        print(f"  {mark} [{set_name}/{arm:<14}] {text[:62]:<62} {spread}"
              f"{'   ' + ', '.join(flags) if flags else ''}")

    if short:
        print(f"\n  !! {short} statement(s) have fewer than {_READINGS} usable "
              f"readings; their unanimity is not comparable")

    # --- E1: Set A replication -------------------------------------------------

    set_a_unanimous = sum(1 for t in _SET_A if unanimous_branch(t))
    print("\n=== E1: Set A replication (the 12 poles, 6 readings each) ===")
    print(f"branch-unanimous : {set_a_unanimous}/12")
    print(f"prior, 3 readings: 7/12")
    if set_a_unanimous <= _PREREG_E1_UNSTABLE_CEILING:
        print(f"INSTABILITY CONFIRMED: {set_a_unanimous}/12 <= "
              f"{_PREREG_E1_UNSTABLE_CEILING}.")
    elif set_a_unanimous == 12:
        print("CONTRADICTED: 12/12 unanimous. The 3-reading drift was an unlucky "
              "sample and the downstream worry it raised does not stand.")
    else:
        print(f"PARTIAL: {set_a_unanimous}/12 sits between "
              f"{_PREREG_E1_UNSTABLE_CEILING + 1} and 11.")

    # --- E2: Set B form hypothesis --------------------------------------------

    by_arm: dict[str, tuple[int, int]] = {}
    for arm in _ARMS:
        members = [t for _s, a, t in _population() if a == arm]
        uni = sum(1 for t in members if unanimous_branch(t))
        by_arm[arm] = (uni, len(members))

    print("\n=== E2: Set B form hypothesis (12 per arm, matched by domain) ===")
    for arm in _ARMS:
        uni, n = by_arm[arm]
        print(f"  {arm:<15} branch-unanimous {uni}/{n}")

    long_uni, long_n = by_arm["LONG_CONCRETE"]
    abs_uni, abs_n = by_arm["SHORT_ABSTRACT"]
    gap = long_uni - abs_uni
    p_form = _fisher_exact_two_sided(
        long_uni, long_n - long_uni, abs_uni, abs_n - abs_uni
    )
    print(f"\ngap (LONG_CONCRETE - SHORT_ABSTRACT) = {gap}")
    print(f"Fisher exact two-sided p = {p_form:.4f}")
    if gap >= _PREREG_E2_GAP and p_form < 0.05:
        print("FORM EFFECT REAL: stability tracks the form of the statement, not "
              "its domain (domains are matched across arms by construction).")
    elif gap <= _PREREG_E2_NULL_GAP:
        print("NO FORM EFFECT: the Set A pattern was not about form. Whatever "
              "makes a statement unstable is something else.")
    else:
        print(f"INDETERMINATE: gap {gap} sits between "
              f"{_PREREG_E2_NULL_GAP + 1} and {_PREREG_E2_GAP - 1}.")

    sc_uni, sc_n = by_arm["SHORT_CONCRETE"]
    print(f"\nSHORT_CONCRETE discriminator: {sc_uni}/{sc_n} unanimous, against "
          f"LONG_CONCRETE {long_uni}/{long_n} and SHORT_ABSTRACT {abs_uni}/{abs_n}.")
    # Gated on E2 firing. "Which arm does SHORT_CONCRETE sit nearer" is only a
    # discriminator if there is an effect to attribute; when the outer arms are
    # a gap of 1 apart it is noise-vs-noise, and an ungated version of this
    # block printed "LENGTH drives stability" off that gap at p=1.0.
    if gap < _PREREG_E2_GAP or p_form >= 0.05:
        print("  -> not interpreted: E2 did not establish a form effect, so there "
              "is nothing for this arm to discriminate between.")
    elif abs(sc_uni - long_uni) < abs(sc_uni - abs_uni):
        print("  -> tracks LONG_CONCRETE: CONCRETENESS drives stability, not length.")
    elif abs(sc_uni - abs_uni) < abs(sc_uni - long_uni):
        print("  -> tracks SHORT_ABSTRACT: LENGTH drives stability, not concreteness.")
    else:
        print("  -> sits exactly between the two arms; this design cannot "
              "separate length from concreteness on these numbers.")

    # --- severity secondaries -------------------------------------------------

    all_texts = _distinct_texts()
    flips = [t for t in all_texts if flips_simple(t)]
    crosses = [t for t in all_texts if crosses_taxonomy(t)]
    domains = [t for t in all_texts if drifts_domain(t)]

    print("\n=== severity secondaries (each a different downstream consequence) ===")
    print(f"SIMPLE/COMPLEX flips : {len(flips)}/{len(all_texts)}"
          "   <- forces HS to 1.0 on some readings only, moving the polarity "
          "across HS_THRESHOLD=0.7")
    for t in flips:
        print(f"    {t}")
    print(f"taxonomy crosses     : {len(crosses)}/{len(all_texts)}"
          "   <- swaps the apex vocabulary wholesale")
    for t in crosses:
        fams = sorted({k[1] for k in keys[t] if k[1] != "Simple"})
        print(f"    {t}  ({'/'.join(fams)})")
    print(f"domain drift         : {len(domains)}/{len(all_texts)}"
          "   <- changes the taught apex even when the branch holds")
    for t in domains:
        doms = sorted({k[2] for k in keys[t] if k[2] != "-"})
        print(f"    {t}  ({'/'.join(doms)})")

    # A dead run must fail loudly rather than reporting 0 instability.
    assert readings, "no readings at all — this is a fixture failure, not a result"
    assert len(readings) == len(texts), (
        f"only {len(readings)} of {len(texts)} texts produced any reading"
    )
