"""
Every generative call in a tetrad refines from the coarser layers, not just Ac-.

A Transformation is generated against the coarser Transformations its edge
descends from ("be more concrete than this broader path"). Until 2026-09-11 only
`_generate_ac_minus` was HANDED that context: the Re side read it out of shared
conversation history without being asked to use it, and Ac+ — generated by a
different concern, in an earlier phase, through `isolate()` — never saw it at all.
Ac+ is copied into the tetrad verbatim, so that was the tetrad's leading position
refining nothing.

These tests are DB-free wherever the prompt builders take plain strings, which is
everywhere that matters here. The end-to-end claim (that the climb makes parents
exist to be found at all) is the probe's: `tests/probe_transformation_recursion.py`.
"""

from __future__ import annotations

from typing import NamedTuple

import pytest

from dialectical_framework.concerns.action_extraction import (
    ActionCandidateResultDto, ActionExtraction)
from dialectical_framework.concerns.transformation_generation import \
    TransformationGeneration
from dialectical_framework.utils.edge_context import (
    REFINE_ACTION, REFINE_REFLECTION, REFINE_TETRAD, coarser_journey_section)

#: Stands in for a rendered ancestry. Distinctive enough that finding it in a
#: prompt cannot be an accident.
HIERARCHY = '"broad start" → "broad end":\n  Action: walk the broader path\n  Reflection: watch the broader path'


def _candidate(statement: str = "take the concrete step") -> ActionCandidateResultDto:
    return ActionCandidateResultDto(
        headline="concrete step",
        statement=statement,
        insight=0.5,
        proactiveness=0.6,
        insight_label="Composition",
        proactiveness_label="Intervention",
        explanation="because",
        haiku="one\ntwo three\nfour",
    )


class _Submitted(NamedTuple):
    """One provider call as this file needs to read it.

    The DTO name is what tells the tetrad's four calls apart, and the whole point
    here is that each of them carries its OWN instruction — so a bare list of
    prompt strings cannot express the assertion.
    """

    dto: str
    prompt: str


def _spy_on_submits(monkeypatch) -> list[_Submitted]:
    """Record every prompt submitted, and keep the real call running.

    Delegating rather than stubbing matters below the pipeline test: the mock
    brain's answer is what lets `ExploreTransformations` reach Phase 2 at all, and
    a spy that returned nothing would leave the Ac-/Re prompts unbuilt — the exact
    calls under test.
    """
    from dialectical_framework.agents.conversation_facilitator import \
        ConversationFacilitator

    records: list[_Submitted] = []
    original = ConversationFacilitator.submit

    async def recording(self, response_model, user_content, **kwargs):
        records.append(
            _Submitted(getattr(response_model, "__name__", str(response_model)),
                       str(user_content))
        )
        return await original(
            self, response_model=response_model, user_content=user_content, **kwargs
        )

    monkeypatch.setattr(ConversationFacilitator, "submit", recording)
    return records


class TestTheSectionItself:
    def test_nothing_coarser_renders_nothing(self):
        """Not a "no ancestry" note: a layer-1 wheel has none to be missing, and
        saying so invites the model to treat a complete answer as a gap."""
        assert coarser_journey_section(None, REFINE_TETRAD) == ""
        assert coarser_journey_section("", REFINE_TETRAD) == ""

    def test_the_hierarchy_and_the_instruction_both_land(self):
        section = coarser_journey_section(HIERARCHY, REFINE_TETRAD)
        assert "<broader_journey>" in section
        assert HIERARCHY in section
        assert REFINE_TETRAD in section
        assert section.endswith("</broader_journey>\n\n")

    def test_the_three_instructions_differ(self):
        """Each names the line of the hierarchy its own position descends from.

        Collapsing them into one sentence is the tempting simplification and it
        loses the whole point: `build_coarser_context` renders BOTH an `Action:`
        and a `Reflection:` line per parent, and Ac+ and Re+ refine different ones.
        """
        assert len({REFINE_TETRAD, REFINE_ACTION, REFINE_REFLECTION}) == 3
        assert "Action line" in REFINE_ACTION
        assert "Reflection line" in REFINE_REFLECTION


@pytest.mark.llm
class TestEveryGenerativeCallIsAsked:
    """The prompt, not the conversation history — history is not an instruction.

    Each of these drives the real prompt builder and reads what was submitted.
    """

    async def test_ac_plus_is_asked(self, monkeypatch):
        """The one that was blind. `ActionExtraction` has its own facilitator and
        `isolate()`s each band, so nothing reaches it through history."""
        records = _spy_on_submits(monkeypatch)
        from dialectical_framework.concerns.ac_re_taxonomy import \
            INSIGHT_CATEGORIES

        category, info = next(iter(INSIGHT_CATEGORIES.items()))
        await ActionExtraction()._generate_candidate_for_category(
            "T: a\nA: b", "", category, info, [], HIERARCHY,
        )

        assert len(records) == 1
        assert HIERARCHY in records[0].prompt
        assert REFINE_ACTION in records[0].prompt

    async def test_ac_minus_is_asked(self, monkeypatch):
        records = _spy_on_submits(monkeypatch)
        await TransformationGeneration()._generate_ac_minus(
            "T: a\nA: b", "", _candidate(), parent_context=HIERARCHY,
        )

        assert len(records) == 1
        assert HIERARCHY in records[0].prompt
        assert REFINE_TETRAD in records[0].prompt

    async def test_the_re_side_is_asked(self, monkeypatch):
        """Measured as having it in the WINDOW and no instruction pointing at it.

        Re shares a facilitator with Ac-, so it read `<broader_journey>` out of
        history and refined by accident of ordering — with nothing enforcing that
        Ac- runs first, and nothing stopping a future edit from isolating this call.
        """
        records = _spy_on_submits(monkeypatch)
        await TransformationGeneration()._generate_re_side(
            "T: c\nA: d", _candidate("their move"), _candidate(),
            "Interpretation", parent_context=HIERARCHY,
        )

        assert len(records) == 1
        assert HIERARCHY in records[0].prompt
        assert REFINE_REFLECTION in records[0].prompt

    async def test_no_ancestry_leaves_every_prompt_as_it_was(self, monkeypatch):
        """The layer-1 case, and the regression guard for three prompts at once."""
        records = _spy_on_submits(monkeypatch)
        gen = TransformationGeneration()
        await gen._generate_ac_minus("T: a\nA: b", "", _candidate())
        await gen._generate_re_side(
            "T: c\nA: d", _candidate("their move"), _candidate(), "Interpretation",
        )
        from dialectical_framework.concerns.ac_re_taxonomy import \
            INSIGHT_CATEGORIES

        category, info = next(iter(INSIGHT_CATEGORIES.items()))
        await ActionExtraction()._generate_candidate_for_category(
            "T: a\nA: b", "", category, info, [],
        )

        assert len(records) == 3
        for record in records:
            assert "<broader_journey>" not in record.prompt


@pytest.mark.llm
class TestScoringIsDeliberatelyNotRefined:
    """HS is a judgement against apexes, and refinement context would bias it.

    HS gates (`HS_THRESHOLD`) and renders, so a score nudged by "be more concrete
    than the broader path" is a different kind of defect from an unrefined
    statement. It shares the tetrad's facilitator and therefore has the hierarchy
    in its window regardless — what this pins is that nothing ASKS it to score
    against the ancestry, which is the part a prompt controls.
    """

    async def test_hs_scoring_carries_no_refinement_instruction(self, monkeypatch):
        from dialectical_framework.concerns.positive_ac_re_apex_derivation import \
            ApexDerivationResultDto

        records = _spy_on_submits(monkeypatch)

        apexes = ApexDerivationResultDto.model_construct(
            ac_plus_apex=_candidate("ac apex"),
            re_plus_apex=_candidate("re apex"),
        )
        await TransformationGeneration()._score_hs("ac", "re", apexes)

        assert len(records) == 1
        assert "<broader_journey>" not in records[0].prompt
        for instruction in (REFINE_TETRAD, REFINE_ACTION, REFINE_REFLECTION):
            assert instruction not in records[0].prompt


@pytest.mark.llm
class TestTheContextTRAVELSThroughTheRealPipeline:
    """Everything above pins the prompt BUILDERS, which is not the same claim.

    A builder test passes whether or not anything HANDS the builder its context —
    and that is the trap this codebase already recorded once, in the rule that a
    "nested scope folds in" test cannot pin the nested scope's existence. So this
    drives the real `ExploreTransformations` against a real committed Wheel and
    asks what the tetrad's four calls actually received.

    Costs ~3s under the mock brain (a wheel over two tensions, transitions and a
    full transformation run) — the same fixture and the same price as
    `test_explore_progress_scope.py::TestTheTwoSkillsInstallTheirOwnScopes`.
    """

    async def test_every_position_is_handed_the_hierarchy_and_the_edge_is_asked_once(
        self, monkeypatch
    ):
        """Two claims, one run, because they are the same wiring seen from both ends.

        The parents are FAKED at the repository, not built: what is under test is
        the path a rendered hierarchy takes from the lookup to each prompt, and
        building real layer-1 Transformations to descend from would add a second
        transformation run to assert nothing extra. The probe
        (`tests/probe_transformation_recursion.py`) owns the claim that real
        ancestry exists to be found.
        """
        from dialectical_framework.agents.explorer.skills.explore_transformations import \
            ExploreTransformations
        from dialectical_framework.graph.nodes.case import Case
        from dialectical_framework.graph.repositories.transformation_repository import \
            TransformationRepository
        from dialectical_framework.graph.scope_context import scope
        from dialectical_framework.utils import edge_context as edge_context_module
        from test_explore_progress_scope import _wheel_over_two_tensions

        case = Case()
        case.commit()
        _, wheel_hash = await _wheel_over_two_tensions(case.sid)

        asked_for: list[str] = []

        def recording_lookup(self, edge):
            asked_for.append(edge.short_hash or str(id(edge)))
            # Empty on purpose. Only `_phase1_for_edge` renders through the patched
            # builder below, so if `TransformationGeneration` re-derives the context
            # itself it reaches the REAL renderer, gets None from an empty list, and
            # its prompts come out bare — which is what makes the assertions below
            # fail on a broken hand-off rather than quietly pass.
            return []

        monkeypatch.setattr(
            TransformationRepository, "find_parent_transformations", recording_lookup
        )
        monkeypatch.setattr(
            edge_context_module, "build_coarser_context", lambda parents: HIERARCHY
        )

        records = _spy_on_submits(monkeypatch)
        with scope(case.sid):
            await ExploreTransformations(wheel_hash=wheel_hash).resolve()

        by_dto: dict[str, list[str]] = {}
        for record in records:
            by_dto.setdefault(record.dto, []).append(record.prompt)

        # Ac+ comes from `ActionExtraction` in Phase 1; the other two from
        # `TransformationGeneration` in Phase 2. Named per DTO because the whole
        # point is that each gets its OWN instruction — a check over all prompts
        # at once would pass on three copies of one sentence.
        for dto, instruction in (
            ("ActionCandidateDto", REFINE_ACTION),
            ("AcMinusCompletionDto", REFINE_TETRAD),
            ("ReSideCompletionDto", REFINE_REFLECTION),
        ):
            submitted = by_dto.get(dto, [])
            assert submitted, (
                f"{dto} was never submitted — the fixture no longer reaches this "
                f"call, so this test proves nothing about it. Saw: {sorted(by_dto)}"
            )
            for prompt in submitted:
                assert HIERARCHY in prompt, f"{dto} got no coarser context"
                assert instruction in prompt, f"{dto} was not asked to refine from it"

        # ...and the same answer is not asked for twice. Phase 2 runs per CANDIDATE
        # (three an edge), so a hand-off that dropped `parent_context` anywhere would
        # show up here as a repeat before it showed up above.
        assert asked_for, "no edge ever asked what it descends from"
        assert len(asked_for) == len(set(asked_for)), (
            "an edge asked for its parents more than once — the lookup hoisted into "
            f"Phase 1 is being re-done downstream: {sorted(asked_for)}"
        )
