"""Pool an effect across every saved run, and see whether it was ever real.

    poetry run python tests/bench/across_runs.py

The bench's unit of publication is a RUN, and a run is 3 replicates. `report.py`
now prints an honest interval inside each one, which is what stopped false
positives being announced — but it cannot catch the other error, the one that
takes a whole archive to see: an effect that is significant-looking in the run
you happen to be reading and absent when the previous fifteen are stacked
against it. Every run in `results/` was generated by a slightly different build,
so this is not a clean meta-analysis; it is the crudest available check on
whether a number is a property of the ARM or a property of that afternoon.

Two effects are pooled, both of which were quoted as findings from r16 alone:

  * **durability** — the composite's opening-vs-return change (`report.py`'s
    "under pressure" block). r16: -1.22.
  * **closure** — the question-ending rate change (`scoring.score_closure`).
    r16: A1.7 -0.03 against A2 +0.31.

Neither survives pooling. That is the point of the script, and the reason it is
committed rather than run once: the next time a single run produces a striking
split, this is the two-minute check that comes before the write-up.

The same machinery then answers the question the bench exists for, and the answer
is the archive's first result that RESOLVES: pooled over 13 single-scenario runs
at the weak tier, A2's composite against the strongest prompt arm in each run is
**-0.473, CI [-0.64,-0.31], negative in 13 of 13**, and all 12 dimensions lose on
intervals that exclude zero. So the headline block below is not a symmetric
"is there an effect" check — it is a standing record of a loss, and the splits
after it are candidate explanations for it, none of which erases it. Kept in the
same file as the refutations on purpose: the pooling that killed two flattering
findings is the pooling that produces this one, and it would be dishonest to run
it only in the direction that hurts.


A MEASUREMENT script, not a test: it prints and exits 0. Free — no LLM, no DB,
pure functions over saved transcripts.
"""

from __future__ import annotations

import math
import statistics as st
import sys
from collections import defaultdict
from pathlib import Path
from typing import Optional

BENCH_DIR = Path(__file__).resolve().parent
RESULTS = BENCH_DIR / "results"
sys.path.insert(0, str(BENCH_DIR.parent))

from bench.models import Comparison, RunRecord  # noqa: E402
from bench.report import _ci95, _fmt_ci, collect_deltas, load_records  # noqa: E402
from bench.runner import score_machine_over  # noqa: E402
from bench.scoring import (  # noqa: E402
    score_internal_prompt_echo,
    score_machinery_leak,
)

#: Prompt arms in descending strength. The comparison that matters is A2 against
#: the STRONGEST prompt arm a run happened to include — beating A0 proves nothing
#: the ablation ladder does not already concede.
_PROMPT_ARMS = ("A1.7", "A1.5", "A1", "A0")


def _stems() -> list[str]:
    """Saved runs worth pooling.

    `-runs` is the same payload under a second name, `-rejudged` is the same cells
    scored twice (pooling it would count one run as two), and `smoke*` are harness
    checks with 1-2 cells. Including any of them inflates n with no new evidence.
    """
    return sorted(
        p.stem
        for p in RESULTS.glob("*.json")
        if not p.stem.endswith(("-runs", "-rejudged"))
        and not p.stem.startswith("smoke")
    )


def sign_test(values: list[float]) -> float:
    """Two-sided sign test p-value for "the median is zero".

    Used alongside the mean's CI because it assumes almost nothing: the runs come
    from different builds with different variances, so a t-interval over them is
    already generous. When the CI and the sign test disagree, believe the sign
    test.
    """
    nonzero = [v for v in values if v != 0]
    n = len(nonzero)
    if not n:
        return 1.0
    k = sum(1 for v in nonzero if v > 0)
    k = max(k, n - k)
    tail = sum(math.comb(n, i) for i in range(k, n + 1)) / 2**n
    return min(1.0, 2 * tail)


def fisher_exact(a1: int, a0: int, b1: int, b0: int) -> float:
    """Two-sided Fisher exact p for a 2x2 count table.

    Used for the record-integrity block, where the measurement is a COUNT of
    events and not a mean of judged scores, so the sign test and the t-interval
    both have nothing to work on. Exact rather than chi-square because the cells
    are small (3 events in one arm) — that is the regime where the approximation
    is worst and the answer matters most.
    """
    n = a1 + a0 + b1 + b0
    if not n or not (a1 + b1) or not (a0 + b0):
        return 1.0

    def probability(x: int) -> float:
        return (
            math.comb(a1 + b1, x)
            * math.comb(a0 + b0, a1 + a0 - x)
            / math.comb(n, a1 + a0)
        )

    observed = probability(a1)
    low = max(0, a1 + a0 - (a0 + b0))
    high = min(a1 + b1, a1 + a0)
    return min(
        1.0,
        sum(
            probability(x)
            for x in range(low, high + 1)
            if probability(x) <= observed + 1e-12
        ),
    )


def _a2_deltas(comparisons: list[Comparison]):
    """(strongest prompt arm's name, its `Deltas` against A2) or None.

    Every pooled block starts here, so the choice of baseline is made once: A2
    against the STRONGEST prompt arm the run contained. Runs differ in which arms
    they included, and picking per-run rather than fixing "A1.7" keeps the two
    Claim-1 runs (A1 only) in the pool instead of silently dropping them — while
    never letting an easy A0 win into the same average.
    """
    by_pair = collect_deltas(comparisons)
    against_a2 = {b.value: (a, b) for a, b in by_pair if a.value == "A2"}
    base = next((a for a in _PROMPT_ARMS if a in against_a2), None)
    if base is None:
        return None
    return base, by_pair[against_a2[base]]


def composite_rows() -> list[tuple[str, str, str, float, int, int]]:
    """(stem, prompt arm, tier, composite, cells, scenarios) per saved set.

    `scenarios` is carried because the multi-scenario `claim2` set is not
    comparable with the rest: it averages `career_offer` (a poor-fit control the
    framework is EXPECTED to lose) into the same number, and its strong-tier cell
    is the archive's -3.13 outlier from a build whose A2 arm was later found
    broken. Reported, then excluded from the pooled line rather than deleted from
    the table, so the exclusion is visible instead of assumed.
    """
    rows: list[tuple[str, str, str, float, int, int]] = []
    for stem in _stems():
        payload = load_records(RESULTS / f"{stem}.json")
        comparisons = [
            Comparison.model_validate(c) for c in payload.get("comparisons") or []
        ]
        if not comparisons:
            continue
        picked = _a2_deltas(comparisons)
        if picked is None:
            continue
        base, deltas = picked
        scenarios = len({c.scenario_key for c in comparisons})
        for tier in deltas.tiers:
            n = deltas.composite_n(tier)
            if n < 2:
                continue
            rows.append(
                (stem, base, tier, deltas.composite(tier) or 0.0, n, scenarios)
            )
    return rows


def dimension_rows(tier: str) -> dict[str, list[float]]:
    """dimension -> one delta per single-scenario run at `tier`.

    One value per RUN, never per cell: the 12 dimensions are repeated measures on
    the same transcript pair, and the cells within a run share a build, a judge
    call pattern and an afternoon. Pooling cells here would report n=132 at the
    weak tier and shrink every interval by ~3x for free.
    """
    per_dimension: dict[str, list[float]] = defaultdict(list)
    for stem in _stems():
        payload = load_records(RESULTS / f"{stem}.json")
        comparisons = [
            Comparison.model_validate(c) for c in payload.get("comparisons") or []
        ]
        if not comparisons or len({c.scenario_key for c in comparisons}) > 1:
            continue
        picked = _a2_deltas(comparisons)
        if picked is None:
            continue
        _base, deltas = picked
        if tier not in deltas.tiers:
            continue
        for dimension in deltas.dimensions():
            gap = deltas.gap(tier, dimension)
            if gap is not None:
                per_dimension[dimension].append(gap)
    return dict(per_dimension)


def dimension_shape(tier: str) -> dict[str, tuple[int, int, int, float, float]]:
    """dimension -> (lost cells, tied, won, mean |delta| when lost, when won).

    The distribution behind `dimension_rows`' means, and it splits the losing
    dimensions into two kinds that need opposite fixes — which the means hide
    completely, because -0.81 and -0.47 look like the same finding at different
    strengths and are not:

      * a UNIFORM TAX — `conversational_fit` loses 131 of 172 cells (76%) and wins
        19, `warmth` 120 and wins 12, each by about 1.1 points. A2 is a bit worse
        nearly everywhere. Whatever causes it is in every reply.
      * BIMODAL — `decision_closure` loses 90 and WINS 51 (30%), `convergence`
        loses 85 and wins 50, and both the losses and the wins are large
        (1.66-1.72 against 1.35-1.44). A2 is not mildly worse at closing; it
        either closes well or badly, roughly 2:1 against.

    Cell-level on purpose, and NOT to be read as a significance claim — that is
    what `dimension_rows` (one value per run) is for. The question here is the
    shape of the distribution, and a run mean cannot have a shape. Deliberately
    kept next to `dimension_rows` so nobody quotes an n=172 interval from it.

    Ruling out the obvious structural causes of the bimodality, all measured and
    all dead: whether the cell has a Decision record (+0.35 unpaired, and it CANNOT
    be paired — only one run in the archive contains cells of both kinds, so the
    split is build date and nothing else); whether it is a returning session
    (+0.33 unpaired, +0.045 CI [-0.83,+0.92] paired within run, 6/13 sets, p=1.00);
    whether it elected `explore` (+0.17, n=20); anchor count (-0.03). The variance
    is in what the reply SAYS, not in which machinery ran — so the judge's own
    notes are the evidence, which is what `judge_notes.py` exists to extract.
    """
    shape: dict[str, list[float]] = defaultdict(list)
    for stem in _stems():
        payload = load_records(RESULTS / f"{stem}.json")
        for raw in payload.get("comparisons") or []:
            comparison = Comparison.model_validate(raw)
            if comparison.tier != tier or comparison.error:
                continue
            arms = (comparison.arm_a.value, comparison.arm_b.value)
            if "A2" not in arms or arms[0] == arms[1]:
                continue
            for dimension, (score_a, score_b) in comparison.scores.items():
                mine, theirs = (
                    (score_a, score_b)
                    if comparison.arm_a.value == "A2"
                    else (score_b, score_a)
                )
                shape[dimension].append(mine - theirs)
    out: dict[str, tuple[int, int, int, float, float]] = {}
    for dimension, values in shape.items():
        lost = [v for v in values if v < 0]
        won = [v for v in values if v > 0]
        out[dimension] = (
            len(lost),
            len(values) - len(lost) - len(won),
            len(won),
            st.mean([abs(v) for v in lost]) if lost else 0.0,
            st.mean(won) if won else 0.0,
        )
    return out


def validity_rows() -> list[tuple[str, float, int, float, int]]:
    """Per run: (stem, clean-cell composite, n, leaky-cell composite, n).

    PAIRED within a run, which is the only form of this split worth printing. The
    unpaired version — every clean cell in the archive against every leaky one —
    reads -0.36 vs -0.66 and looks like leaks explain most of the loss, but the
    two groups are not drawn from the same runs: the cleanest cells come from the
    latest builds, which also fixed everything else. Comparing inside a run holds
    the build fixed, and the effect drops to +0.25 with an interval covering zero
    (12/14 sets, sign test p=0.79). Leaks are a real defect and a poor
    explanation for the composite.

    A cell counts as leaky if its A2 record shows any `score_machinery_leak` or
    `score_internal_prompt_echo` hit in any session.
    """
    rows: list[tuple[str, float, int, float, int]] = []
    for stem in _stems():
        payload = load_records(RESULTS / f"{stem}.json")
        comparisons = [
            Comparison.model_validate(c) for c in payload.get("comparisons") or []
        ]
        if not comparisons:
            continue
        defects: dict[tuple, int] = {}
        for record in (RunRecord.model_validate(r) for r in payload["runs"]):
            if record.arm.value != "A2":
                continue
            defects[
                (record.tier, record.scenario_key, record.replicate, record.branch)
            ] = sum(
                len(score_machinery_leak(s)) + len(score_internal_prompt_echo(s))
                for s in record.sessions
            )
        clean: list[float] = []
        leaky: list[float] = []
        for comparison in comparisons:
            if comparison.error or comparison.arm_a.value != "A2":
                continue
            if not comparison.scores:
                continue
            composite = st.mean(
                [a - b for a, b in comparison.scores.values()]
            )
            keys = [
                k
                for k in defects
                if k[0] == comparison.tier
                and k[1] == comparison.scenario_key
                and k[2] == comparison.replicate
            ]
            if not keys:
                continue
            # A judged session belongs to a branch when its label names one; a
            # base session ("decide") is shared, so take the quieter reading
            # rather than blaming it for a defect that happened downstream.
            matching = [
                k for k in keys if k[3] and comparison.session_label.endswith(k[3])
            ] or keys
            hits = min(defects[k] for k in matching)
            (clean if hits == 0 else leaky).append(composite)
        if clean and leaky:
            rows.append(
                (stem, st.mean(clean), len(clean), st.mean(leaky), len(leaky))
            )
    return rows


def election_rows() -> list[tuple[str, str, float, float]]:
    """Per (run, tier): (stem, tier, share of A2 cells that ran explore/deepen, composite).

    `explore` election is the bench's longest-standing suspect — the framework
    cannot help through a pathway it never builds. The correlation is real
    (+0.36) and CONFOUNDED beyond use: every set where the share clears 0.5 is a
    strong-tier run, so "elected explore" and "ran on the better model" are the
    same column. Printed with that stated, because the confound is the finding —
    testing it needs a weak-tier run where election is forced, not more pooling.
    """
    rows: list[tuple[str, str, float, float]] = []
    for stem in _stems():
        payload = load_records(RESULTS / f"{stem}.json")
        comparisons = [
            Comparison.model_validate(c) for c in payload.get("comparisons") or []
        ]
        if not comparisons or len({c.scenario_key for c in comparisons}) > 1:
            continue
        picked = _a2_deltas(comparisons)
        if picked is None:
            continue
        _base, deltas = picked
        a2 = [r for r in (RunRecord.model_validate(x) for x in payload["runs"])
              if r.arm.value == "A2"]
        if not a2:
            continue
        elected = sum(
            1
            for r in a2
            if any(
                name.startswith(("explore", "deepen"))
                for s in r.sessions
                for t in s.turns
                for name in t.tool_calls
            )
        )
        for tier in deltas.tiers:
            if deltas.composite_n(tier) >= 2:
                rows.append(
                    (stem, tier, elected / len(a2), deltas.composite(tier) or 0.0)
                )
    return rows


def _corr(xs: list[float], ys: list[float]) -> Optional[float]:
    if len(xs) < 3:
        return None
    mx, my = st.mean(xs), st.mean(ys)
    denominator = (
        sum((x - mx) ** 2 for x in xs) * sum((y - my) ** 2 for y in ys)
    ) ** 0.5
    if not denominator:
        return None
    return sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / denominator


def record_cells() -> dict[str, list[bool]]:
    """Per arm, one bool per CELL: did it falsely claim a record at least once?

    The significance companion to `record_rows`, and collapsed to cell level on
    purpose. Requests inside one cell are not independent — they are the same
    scripted conversation, and an arm that lies once in it tends to lie again — so
    a test over 168 requests would overstate its own n. One bool per cell is the
    conservative unit, and `phantom_claims > 0` is the event.

    Arms are pooled to A2-vs-prose because the prose arms are one capability class
    here (no store, so nothing but their own words to offer) and splitting them
    three ways only shrinks cells the exact test is already straining on.
    """
    from bench.scoring import score_phantom_record

    cells: dict[str, list[bool]] = defaultdict(list)
    for stem in _stems():
        payload = load_records(RESULTS / f"{stem}.json")
        for run in (RunRecord.model_validate(r) for r in payload["runs"]):
            if not run.sessions:
                continue
            score = score_phantom_record(
                run.sessions, record_exists=bool(run.decision_hashes)
            )
            if not score.requests:
                continue
            arm = "A2" if run.arm.value == "A2" else "prose"
            cells[arm].append(score.phantom_claims > 0)
    return cells


def record_rows() -> dict[str, dict[str, int]]:
    """Per arm, pooled over the whole archive: what happened when the person asked
    for their decision in writing.

    The one block here that pools CELLS rather than runs, and the exception is
    principled: this is not a judged score with a per-run build/judge effect, it
    is a count of an obligation the person stated in their own words against a
    fact on the graph. There is nothing for an afternoon to shift. Every saved set
    contributes, `smoke*` included via `_stems()`'s filter only — a 2-cell harness
    check still holds a real request and a real record.

    Not a delta, either, and it must not be read as one: `record` is a capability
    the prose arms do not have, so their 0 is not a defect. PHANTOM is the
    comparable column — asserting a record exists when none does — and it is where
    the arms genuinely part company.
    """
    from bench.scoring import score_phantom_record

    totals: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    for stem in _stems():
        payload = load_records(RESULTS / f"{stem}.json")
        for run in (RunRecord.model_validate(r) for r in payload["runs"]):
            if not run.sessions:
                continue
            score = score_phantom_record(
                run.sessions, record_exists=bool(run.decision_hashes)
            )
            if not score.requests:
                continue
            bucket = totals[run.arm.value]
            for field in (
                "requests",
                "honoured",
                "phantom_claims",
                "typed_only",
                "withheld_openly",
            ):
                bucket[field] += getattr(score, field)
    return totals


def durability_rows() -> list[tuple[str, str, str, float, int]]:
    """(stem, arm pair, tier, mean composite change, replicates) per saved set."""
    rows: list[tuple[str, str, str, float, int]] = []
    for stem in _stems():
        payload = load_records(RESULTS / f"{stem}.json")
        comparisons = [
            Comparison.model_validate(c) for c in payload.get("comparisons") or []
        ]
        if not comparisons:
            continue
        for (arm_a, arm_b), deltas in collect_deltas(comparisons).items():
            for tier in sorted({c.tier for c in comparisons}):
                changes = deltas.pressure_changes(tier)
                if len(changes) < 2:
                    continue
                rows.append(
                    (
                        stem,
                        f"{arm_a.value} v {arm_b.value}",
                        tier,
                        st.mean(changes),
                        len(changes),
                    )
                )
    return rows


def closure_rows() -> list[tuple[str, str, float, float, int]]:
    """(stem, prompt arm, its mean change, A2's mean change, cells) per run.

    Machine scores are RE-COMPUTED from the transcripts rather than read from the
    saved `machine` block: `closure` postdates every run in the archive, and the
    whole reason a machine scorer is worth having is that it applies backwards for
    free.
    """
    rows: list[tuple[str, str, float, float, int]] = []
    for stem in _stems():
        payload = load_records(RESULTS / f"{stem}.json")
        runs = [RunRecord.model_validate(r) for r in payload["runs"]]
        machine = score_machine_over(runs, {})
        per_arm: dict[str, list[float]] = defaultdict(list)
        for key, scores in machine.items():
            change = scores.closure.rate_change if scores.closure else None
            if change is not None:
                per_arm[key.split("|")[0]].append(change)
        if "A2" not in per_arm:
            continue
        base = next((a for a in _PROMPT_ARMS if a in per_arm), None)
        if base is None:
            continue
        rows.append(
            (stem, base, st.mean(per_arm[base]), st.mean(per_arm["A2"]), len(per_arm["A2"]))
        )
    return rows


def _summarise(label: str, values: list[float], expect: str) -> None:
    if len(values) < 2:
        print(f"  {label}: too few sets to pool ({len(values)})")
        return
    positive = sum(1 for v in values if v > 0)
    print()
    print(
        f"  {label}: n={len(values)} sets  mean {st.mean(values):+.3f}  "
        f"sd {st.stdev(values):.3f}  {_fmt_ci(_ci95(values))}"
    )
    print(
        f"  {'':{len(label)}}  positive in {positive}/{len(values)}  "
        f"sign test p={sign_test(values):.3f}"
    )
    print(f"  -> {expect}")


def _headline() -> None:
    """The pooled composite — the archive's one resolved result, and a loss."""
    print("=" * 74)
    print("COMPOSITE — A2 against the strongest prompt arm, one value per run")
    print("=" * 74)
    rows = composite_rows()
    for stem, base, tier, composite, cells, scenarios in rows:
        flag = "  (multi-scenario: excluded below)" if scenarios > 1 else ""
        print(
            f"  {stem:34} A2 v {base:5} {tier:7} {composite:+.3f}  "
            f"(cells {cells:2}){flag}"
        )
    for tier in ("weak", "strong"):
        values = [r[3] for r in rows if r[2] == tier and r[5] == 1]
        _summarise(
            f"composite/{tier}",
            values,
            "NEGATIVE AND RESOLVED — the framework arm loses to a prompt at this\n"
            "     tier, and it is not one afternoon."
            if tier == "weak"
            else "does not resolve, and is ~7x smaller than the weak-tier loss. Four\n"
            "     sets cannot tell 'the deficit closes on a better model' from noise,\n"
            "     and that is the cheapest open question in the bench: the claim the\n"
            "     product needs is a strong-tier one.",
        )


def _dimensions() -> None:
    print()
    print("=" * 74)
    print("DIMENSIONS — weak tier, one delta per run, worst first")
    print("=" * 74)
    per_dimension = dimension_rows("weak")
    resolved = 0
    for dimension, values in sorted(
        per_dimension.items(), key=lambda kv: st.mean(kv[1])
    ):
        ci = _ci95(values)
        mark = " *" if ci and (ci[0] > 0 or ci[1] < 0) else "  "
        resolved += mark == " *"
        print(
            f"  {dimension:24} n={len(values):2} {st.mean(values):+.3f} "
            f"{_fmt_ci(ci)}{mark} sign p={sign_test(values):.3f}"
        )
    print(f"  * = interval excludes zero ({resolved} of {len(per_dimension)})")
    print()
    print("  distribution behind those means (CELL level — shape only, not a CI):")
    shape = dimension_shape("weak")
    print(
        f"    {'dimension':24} {'lost':>5} {'tied':>5} {'won':>5}"
        f" {'|delta| lost':>13} {'won':>6}"
    )
    for dimension, _values in sorted(
        per_dimension.items(), key=lambda kv: st.mean(kv[1])
    ):
        if dimension not in shape:
            continue
        lost, tied, won, size_lost, size_won = shape[dimension]
        print(
            f"    {dimension:24} {lost:5} {tied:5} {won:5}"
            f" {size_lost:13.2f} {size_won:6.2f}"
        )
    print(
        "    -> TWO KINDS OF LOSS, needing opposite fixes, and the means hide the\n"
        "       difference because -0.80 and -0.55 read as one finding at two\n"
        "       strengths. (a) A UNIFORM TAX on conversational_fit (loses 76% of\n"
        "       cells, wins 11%) and warmth (70%, wins 7%) — the only two dimensions\n"
        "       where A2 almost never wins at all. A2 is slightly worse nearly\n"
        "       everywhere, so the cause is in every reply, and no single cell will\n"
        "       show it. (b) BIMODAL closure: decision_closure and convergence lose\n"
        "       half their cells but A2 WINS 30% outright, and both tails are larger\n"
        "       (1.66-1.72 lost against 1.35-1.44 won). It does not close mildly\n"
        "       badly; it either closes well or fails hard, about 2:1 against — so\n"
        "       there are winning cells to read against losing ones, which the\n"
        "       uniform tax denies. Note also actionability's -0.09 is not a small\n"
        "       deficit but a genuine COIN FLIP (71 lost, 74 won, both tails ~1.6):\n"
        "       the framework's own home dimension is high-variance, not neutral.\n"
        "       Every structural explanation for the bimodality is dead (see\n"
        "       `dimension_shape`) — the variance is in what the reply SAYS, so read\n"
        "       `judge_notes.py`, not more counts."
    )
    print(
        "  -> 11 of 12 lose on a resolved interval, so this is not one bad subscale.\n"
        "     The ORDER is the diagnosis: the largest losses are the base model's own\n"
        "     turf (conversational_fit, cross_turn_coherence, warmth) and the closing\n"
        "     turns (decision_closure, convergence), while the framework's own\n"
        "     dimensions lose least (actionability -0.09 unresolved,\n"
        "     blindspot_specificity -0.24, non_triviality -0.31). Read plainly: the\n"
        "     dialectics are not adding nothing, they are being paid for in\n"
        "     conversation quality — and at this tier the price exceeds the gain."
    )


def _records() -> None:
    """The other direction: the archive's one clean framework win.

    Placed immediately after the loss it does not cancel. The composite says the
    framework arm is worse counsel at the weak tier; this says it is the only arm
    that can keep a promise the person states out loud. Both are true, and a
    write-up that carries one without the other is advocacy.
    """
    print()
    print("=" * 74)
    print("PROMISED RECORDS — pooled over every saved cell, by arm")
    print("=" * 74)
    totals = record_rows()
    for arm in sorted(totals, key=lambda a: (a != "A2", a)):
        counts = totals[arm]
        asked = counts["requests"]
        silent = (
            asked
            - counts["honoured"]
            - counts["phantom_claims"]
            - counts["typed_only"]
            - counts["withheld_openly"]
        )
        print(
            f"  {arm:5} asked {asked:3}  record {counts['honoured']:3}"
            f" ({counts['honoured'] / asked:4.0%})"
            f"  PHANTOM {counts['phantom_claims']:3}"
            f" ({counts['phantom_claims'] / asked:4.0%})"
            f"  typed {counts['typed_only']:3}  refused {counts['withheld_openly']:2}"
            f"  silent {silent:3}"
        )
    prose = [a for a in totals if a != "A2"]
    prose_asked = sum(totals[a]["requests"] for a in prose)
    prose_phantom = sum(totals[a]["phantom_claims"] for a in prose)
    a2 = totals.get("A2", {})
    cells = record_cells()
    a2_cells, prose_cells = cells.get("A2", []), cells.get("prose", [])
    p_value = fisher_exact(
        sum(a2_cells),
        len(a2_cells) - sum(a2_cells),
        sum(prose_cells),
        len(prose_cells) - sum(prose_cells),
    )
    print()
    print(
        f"  cells telling at least one lie: A2 {sum(a2_cells)}/{len(a2_cells)}"
        f" ({sum(a2_cells) / len(a2_cells):.0%})  vs  prose"
        f" {sum(prose_cells)}/{len(prose_cells)}"
        f" ({sum(prose_cells) / len(prose_cells):.0%})   Fisher exact p={p_value:.4f}"
    )
    print(
        "  -> The `record` column is a CAPABILITY, not a score: a reply-only arm has\n"
        "     nowhere to put one, so its 0 is not a defect and this is not a delta.\n"
        f"     PHANTOM is the comparable column — prose arms {prose_phantom}/{prose_asked}"
        f" ({prose_phantom / prose_asked:.0%}) against\n"
        f"     A2 {a2.get('phantom_claims', 0)}/{a2.get('requests', 0)}"
        f" ({a2.get('phantom_claims', 0) / max(1, a2.get('requests', 0)):.0%}):"
        " told the person their decision was written\n"
        "     down when nothing was. `typed` is the honest ceiling of a reply-only arm\n"
        "     and is charged to nobody.\n"
        "     Unusually for this bench the result is not judged — it is checkable\n"
        "     against the person's own words and the graph — and it is machinery, not\n"
        "     prompt: `_DECISION_READINESS` already forbids exactly this failure, three\n"
        "     rounds of strengthening it moved nothing, and what fixed A2's own residue\n"
        "     was `_repair_unrecorded_decision` writing the record when the model would\n"
        "     not elect the call (un-called requests with a real record: 9/22 before the\n"
        "     seam, 18/21 after)."
    )


def _explanations() -> None:
    print()
    print("=" * 74)
    print("CANDIDATE EXPLANATIONS — neither erases the loss above")
    print("=" * 74)
    rows = validity_rows()
    print("  validity defects, PAIRED within each run (clean cells - leaky cells):")
    for stem, clean, clean_n, leaky, leaky_n in rows:
        print(
            f"    {stem:32} clean {clean:+.3f} (n={clean_n:2})  "
            f"leaky {leaky:+.3f} (n={leaky_n:2})  diff {clean - leaky:+.3f}"
        )
    _summarise(
        "  clean - leaky",
        [c - l for _s, c, _cn, l, _ln in rows],
        "does not resolve. The unpaired split (-0.36 clean vs -0.66 leaky) is\n"
        "     confounded with build date; held inside a run, leaks do not account for\n"
        "     the composite. Fix them because they are defects, not for the score.",
    )

    print()
    print("  explore/deepen election share vs the run's composite:")
    elections = election_rows()
    for stem, tier, share, composite in elections:
        print(f"    {stem:32} {tier:7} share {share:.2f}  composite {composite:+.3f}")
    correlation = _corr([e[2] for e in elections], [e[3] for e in elections])
    high = [e[3] for e in elections if e[2] >= 0.5]
    low = [e[3] for e in elections if e[2] < 0.5]
    if correlation is not None:
        print(f"    corr {correlation:+.3f} over n={len(elections)}")
    if high and low:
        print(
            f"    share>=0.5: n={len(high)} mean {st.mean(high):+.3f} "
            f"{_fmt_ci(_ci95(high))}"
        )
        print(
            f"    share <0.5: n={len(low)} mean {st.mean(low):+.3f} "
            f"{_fmt_ci(_ci95(low))}"
        )
    tiers_high = {e[1] for e in elections if e[2] >= 0.5}
    print(
        "    -> UNUSABLE as evidence: "
        + (
            f"every set above 0.5 is {'/'.join(sorted(tiers_high))} tier, so election\n"
            "       and model strength are one column. To test it, force election on a\n"
            "       weak-tier run."
            if tiers_high <= {"strong"}
            else "check the tier composition before reading this."
        )
    )


def main() -> int:
    _headline()
    _dimensions()
    _records()
    _explanations()

    print()
    print("=" * 74)
    print("DURABILITY — composite change from the opening to the returning session")
    print("=" * 74)
    rows = durability_rows()
    for stem, pair, tier, change, n in rows:
        print(f"  {stem:34} {pair:12} {tier:7} {change:+.2f}  (reps {n})")
    _summarise(
        "durability",
        [r[3] for r in rows],
        "r16's -1.22 does not replicate: it is the archive's most extreme value "
        "in either\n     direction, and the pooled effect is indistinguishable "
        "from zero. The split is a\n     useful DECOMPOSITION; it was not a "
        "finding.",
    )

    print()
    print("=" * 74)
    print("CLOSURE — change in the share of turns ending on a question")
    print("=" * 74)
    crows = closure_rows()
    for stem, base, base_v, a2_v, n in crows:
        print(
            f"  {stem:34} {base:5} {base_v:+.2f} -> A2 {a2_v:+.2f}   "
            f"diff {a2_v - base_v:+.2f}  (cells {n})"
        )
    _summarise(
        "closure",
        [a2 - b for _s, _b, b, a2, _n in crows],
        "A2 does drift toward asking rather than advising on return, but so does "
        "the prompt\n     arm: the DIFFERENCE is small and does not resolve. r16's "
        "+0.31-vs--0.03 was one\n     draw. Do not prompt-fix an arm difference "
        "this has not established.",
    )

    print()
    print(
        "Standing caveat: every run here was produced by a different build, so\n"
        "this pools apples and pears on purpose. It is strong evidence AGAINST an\n"
        "effect (a real arm property should survive its own codebase changing) and\n"
        "weak evidence for one."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
